### ISSUE TITLE
Could not run project in terminal

### ISSUE THREAD

**Issue by Yuxin-W** [googlecreativelab/semi-conductor#2]
Dear googlecreativelab

Hi,

I downloaded the project file and followed the 'quick start' steps to start it, but when I preview the effects on localhost, it stuck on the loading page, meanwhile, the terminal gave out several warnings like: could not load source file "......".

Could you please kindly give a look and tell me what to do to solve it ?

Sry to bother and many thanks

Yuxin

<img width="570" alt="Screenshot 2020-04-25 at 08 59 12" src="https://user-images.githubusercontent.com/46967277/80267370-0ea2e780-86d3-11ea-8db0-bf269e864260.png">

**Comment by Yuxin-W** [comment]
solved

**Comment by ashish0910** [comment]
Hello @Yuxin-W ,
Can you please share the procedure to solve this issue.
Thanks

**Comment by badrikomma** [comment]
Hello @ashish0910  and @Yuxin-W ,

Can you please tell me how did you overcome the issue, even I am getting the same kind of error.
It would be a great help

Thank you

**Comment by amrbinniyaz** [comment]
Could not load source file "../src/constraints.ts" in source map of "../node_modules/@tensorflow/tfjs-layers/dist/constraints.js".
